# Generated by Django 3.1.2 on 2020-10-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocketlaunch', '0003_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name_plural': 'Statuses'},
        ),
    ]
