# Generated by Django 3.1.2 on 2020-10-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocketlaunch', '0004_auto_20201017_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost', models.IntegerField(null=True)),
                ('time_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocketlaunch.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocketlaunch.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocketlaunch.status')),
            ],
            options={
                'verbose_name_plural': 'Launches',
                'ordering': ['id'],
            },
        ),
    ]
